name: flutter_learn
description: A new flutter application project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^2.0.9
  dio: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - images/
  application:
    androidPackage: com.example.flutterlearn
    iosBundleIdentifier: com.example.flutterLearn
